# Generated by Django 6.0.4 on 2026-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon (emoji yoki FontAwesome class)')),
                ('number', models.CharField(help_text='Masalan: 150+', max_length=50, verbose_name='Raqam')),
                ('label', models.CharField(help_text='Masalan: Bajarilgan loyihalar', max_length=255, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Yutuq',
                'verbose_name_plural': 'Yutuqlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qildi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kompaniya nomi')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logotipi')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Telefon 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=500, verbose_name='Manzil')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('behance', models.URLField(blank=True, verbose_name='Behance')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('map_embed_url', models.TextField(blank=True, verbose_name='Xarita embed URL')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('role', models.CharField(max_length=255, verbose_name='Lavozimi')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Rasmi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': 'Jamoa',
                'ordering': ['order'],
            },
        ),
    ]
