# Generated by Django 6.0.4 on 2026-04-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitesettings_behance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='Haqimda rasmi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='Hero rasmi'),
        ),
    ]
