# Generated by Django 6.0.4 on 2026-04-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_about_image_sitesettings_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='Logotip'),
        ),
    ]
