# Generated by Django 6.0.4 on 2026-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Demo video'),
        ),
    ]
